[phases.setup]
nixPkgs = [
    "chromium",
    "nss",
    "nspr",
    "atk",
    "cups",
    "dbus",
    "expat",
    "libdrm",
    "libxcb",
    "xorg.libX11",
    "xorg.libXcomposite",
    "xorg.libXdamage",
    "xorg.libXext",
    "xorg.libXfixes",
    "xorg.libXrandr",
    "xorg.libxkbcommon",
    "mesa",
    "pango",
    "cairo",
    "alsa-lib"
]

[phases.build]
cmds = ["npm ci", "npx playwright install chromium"]

[start]
cmd = "node scheduler.js"